simplify rrd clone process
there is a command line option to specify a template

also trying to find out what the root cause of the following error
messages could be:

  rrdtool.OperationalError: /tmp/clone.rrd: illegal attempt to update
    using time 1674767333 when last update time is 1674777600 (minimum
    one second step)