switch to different mail sending action
this one seems to be maintained. also the old one did not fail on
    Error: Server terminates connection. response=421-4.7.0 Try again later, closing connection. (EHLO)